name: rick_and_morty
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  json_annotation: ^4.9.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
